services:
  minio:
    image: quay.io/minio/minio
    container_name: 'minio_container'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: rootadmin
      MINIO_ROOT_PASSWORD: root12345
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        echo Waiting for MinIO to start...;
        sleep 5;
        mc alias set minio http://minio:9000 rootadmin root12345;
        mc mb minio/our-bucket;
        exit 0;
      "

  minio-db:
    image: 'postgres:14'
    container_name: 'minio_db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5050:5432
